export const TYPE_INCREASE = "TYPE_INCREASE";
export const TYPE_DECREASE = "TYPE_DECREASE";

export const BUTTON_TYPE_NUMBER = "BUTTON_TYPE_NUMBER";
export const BUTTON_TYPE_GRAVITY = "BUTTON_TYPE_GRAVITY";